use highlandcoffee;
INSERT INTO Branch (branch_id, branch_name, address) VALUES
(1,'Highlands Handico','Tòa nhà Handico, Phạm Hùng, Mễ Trì'),
(2,'Highlands Vincom Skylake','Tầng 1, Vincom Skylake, Phạm Hùng'),
(3,'Highlands Viglacera','Tòa nhà Viglacera, số 1 Đại lộ Thăng Long'),
(4,'Highlands The Manor','Tòa nhà The Manor, Mễ Trì'),
(5,'Highlands Florence','28 Trần Hữu Dực, Cầu Diễn'),
(6,'Highlands Nguyễn Cơ Thạch','Số 19 Nguyễn Cơ Thạch, Mỹ Đình 2'),
(7,'Highlands A1 Nguyễn Cơ Thạch','Tòa nhà A1, Nguyễn Cơ Thạch'),
(8,'Highlands Sunsquare','21 Lê Đức Thọ, Mỹ Đình 2'),
(9,'Highlands Dolphin Plaza','Số 6 Nguyễn Hoàng, Mỹ Đình'),
(10,'Highlands Ecolife','Tòa nhà Ecolife, 58 Tố Hữu'),
(11,'Highlands Fivimart Mỹ Đình','89 Lê Đức Thọ, Mỹ Đình'),
(12,'Highlands HD Mon','Tòa nhà HD Mon, Hàm Nghi'),
(13,'Highlands Golden Field','Ngã tư Hàm Nghi - Nguyễn Cơ Thạch'),
(14,'Highlands Vinhomes Gardenia','Hàm Nghi, Mỹ Đình'),
(15,'Highlands Landmark 72','Tòa nhà Keangnam, Phạm Hùng'),
(16,'Highlands Trần Bình','138 Trần Bình, Mỹ Đình'),
(17,'Highlands Đại Mỗ','Tố Hữu, Đại Mỗ'),
(18,'Highlands Trần Hữu Dực','30 Trần Hữu Dực'),
(19,'Highlands Smart City','TTTM Vincom Mega Mall Smart City'),
(20,'Highlands Lê Đức Thọ','45 Lê Đức Thọ'),
(21,'Highlands Xuân Thủy','241 Xuân Thủy, Dịch Vọng Hậu'),
(22,'Highlands Cầu Giấy','302 Cầu Giấy'),
(23,'Highlands Discovery','302 Cầu Giấy'),
(24,'Highlands Trần Thái Tông','90 Trần Thái Tông'),
(25,'Highlands Duy Tân','82 Duy Tân, Dịch Vọng Hậu'),
(26,'Highlands Láng Hạ','57 Láng Hạ'),
(27,'Highlands Nguyễn Chánh','148 Nguyễn Chánh'),
(28,'Highlands Vũ Phạm Hàm','Chung cư G4, Vũ Phạm Hàm'),
(29,'Highlands Trần Duy Hưng','222 Trần Duy Hưng'),
(30,'Highlands Trung Hòa','117 Trần Duy Hưng'),
(31,'Highlands DCapitale','Tòa C1 D''Capitale Trần Duy Hưng'),
(32,'Highlands Trung Hòa Nhân Chính','27 Trần Duy Hưng'),
(33,'Highlands Trung Kính','177 Trung Kính'),
(34,'Highlands Yên Hòa','Trung Kính, Yên Hòa'),
(35,'Highlands Phùng Chí Kiên','Số 1 Phùng Chí Kiên'),
(36,'Highlands Lạc Long Quân','395 Lạc Long Quân'),
(37,'Highlands Hồ Tùng Mậu','136 Hồ Tùng Mậu'),
(38,'Highlands Goldmark City','304 Hồ Tùng Mậu'),
(39,'Highlands Xuân La','161 Xuân La'),
(40,'Highlands Ngoại Giao Đoàn','Tòa nhà N03-T7 Ngoại Giao Đoàn'),
(41,'Highlands Nguyễn Trãi','495 Nguyễn Trãi'),
(42,'Highlands Thanh Xuân','275 Nguyễn Trãi'),
(43,'Highlands Vũ Trọng Phụng','69 Vũ Trọng Phụng'),
(44,'Highlands Royal City','TTTM Royal City, Nguyễn Trãi'),
(45,'Highlands Lê Văn Lương','27 Lê Văn Lương'),
(46,'Highlands Hoàng Đạo Thúy','Ngã tư Lê Văn Lương - Hoàng Đạo Thúy'),
(47,'Highlands Nguyễn Huy Tưởng','1 Nguyễn Huy Tưởng'),
(48,'Highlands Khuất Duy Tiến','15 Khuất Duy Tiến'),
(49,'Highlands Ngụy Như Kon Tum','102 Ngụy Như Kon Tum'),
(50,'Highlands Lê Trọng Tấn','3 Lê Trọng Tấn');
SELECT * FROM Branch;
